/* istanbul ignore file */
import type { Meta, StoryObj } from '@storybook/react';
import { Icon } from '@lumia/icons';

const registryIcons = [
  { id: 'home', label: 'Home' },
  { id: 'user', label: 'User' },
  { id: 'sparkle', label: 'Sparkle (custom)' },
  { id: 'chat-bubble', label: 'Chat bubble (custom)' },
];

const meta = {
  title: 'Foundations/Icons',
  component: Icon,
  tags: ['autodocs'],
  args: {
    size: 24,
    className: 'text-primary-600',
  },
  parameters: {
    layout: 'centered',
  },
} satisfies Meta<typeof Icon>;

export default meta;
type Story = StoryObj<typeof Icon>;

export const Registry: Story = {
  render: (args) => (
    <div className="grid grid-cols-2 gap-6 bg-background p-6 sm:grid-cols-4">
      {registryIcons.map((icon) => (
        <div key={icon.id} className="flex flex-col items-center gap-3">
          <Icon {...args} id={icon.id} />
          <span className="text-sm text-foreground">{icon.label}</span>
        </div>
      ))}
    </div>
  ),
  parameters: {
    docs: {
      description: {
        story:
          'Icons are registered in memory and can be referenced by id anywhere in the system. Custom icons generated by the CLI appear alongside curated Lucide icons.',
      },
    },
  },
};

export const Sizes: Story = {
  render: () => (
    <div className="flex items-center gap-4 bg-background p-6">
      <Icon id="sparkle" size={16} className="text-primary-500" />
      <Icon id="sparkle" size={24} className="text-primary-600" />
      <Icon id="sparkle" size={32} className="text-primary-700" />
    </div>
  ),
};
